### ISSUE TITLE
Missing sound file - dsqu.wav

### ISSUE THREAD

**Issue by JennaMalkin** [gantt42/Children-of-Capillata#28]
X-posting from http://creaturescaves.com/forum.php?view=12&thread=6830 :

the empathetic vendor is missing a sound file for the bouncy ball

Runtime error in agent 2 21 31 script 2 21 31 6 unique id 6215 
Sound file missing
dsqu.wav
... 0 or rand 0 10 eq 0 {@}sndc "dsqu" endi ]

**Comment by gantt42** [comment]
Should be fixed with 300ea336daee365029ed368c42ed9006fa38545c
